medic/medic/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
]

medic/web/urls.py
from django.urls import path
from . import views

app_name= "web"
urlpatterns = [
    path('symptoms/', views.symptoms, name = 'symptoms'),
    path('diagnosis/<str:diagnosis>', views.diagnosis, name = 'diagnosis'),
    path('processing/', views.processing, name = 'processing'),
    path('login/', views.login, name = 'login'),
    path('login_auth/', views.login_auth, name = 'login_auth'),
    path('officials/', views.officials, name = 'officials'),
    path('email/', views.email, name = 'email'),
    # path('add_diagnosis/', views.add_diagnosis, name = 'add_diagnosis'),
]

medic/web/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Official_Diagnosis(models.Model):
    illness = models.CharField(max_length=250)
    diagnosis = models.CharField( max_length=500)
    offical = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return self.offical.username+"("+self.illness+")"

medic/web/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from pandas import read_csv
import requests
from pandas.io.html import read_html
from django.contrib.auth import authenticate
from django.contrib.auth import login as lg
from django.contrib.auth.decorators import login_required
from web.models import Official_Diagnosis
from django.contrib.auth.models import User
from django.core.mail import send_mail
# from django.contrib.staticfiles.storage import staticfiles_storage as storage
# Create your views here.


def symptoms(request):
    symptoms = read_csv("web/datafiles/symptoms.csv", header=None).values[:, 0]
    return render(request, 'web/symptoms.html', {'symptoms_list': symptoms})


def diagnosis(request, diagnosis):
    od_list = Official_Diagnosis.objects.filter(illness=diagnosis)

    # print(ob_list)

    def api_get(PRAMS):
        S = requests.Session()
        URL = "https://en.wikipedia.org/w/api.php"
        try:
            R = S.get(url=URL, params=PRAMS)
            print(R)
        except:
            print("#######----her")

            return None
        else:
            DATA = R.json()
            return DATA

    def get_title(diagnosis):
        # diagnosis = diagnosis
        PRAMS = {
            "action": "query",
            "format": "json",
            "list": "search",
            "redirects": 1,
            "srsearch": diagnosis,
            "srnamespace": "0",
            "srlimit": "1",
            "srprop": "snippet",
            "srsort": "relevance"
        }
        DATA = api_get(PRAMS)
        if DATA:
            out = DATA['query']['search']
            if out == [] and '(' in diagnosis:
                diagnosis = diagnosis.replace('(', '|')
                diagnosis = diagnosis.replace(')', '|')
                search_keys = diagnosis.split('|').reverse()
                for a in search_keys:
                    out = get_title(a)
                    if out:
                        break

            return out[0]

    def get_info(page):
        PRAMS = {
            "action": "query",
            "format": "json",
            "prop": "description|pageimages",
            "titles": page["title"].replace(' ', '_'),
            "piprop": "name|original"
        }
        pageid = str(page["pageid"])
        print(pageid)
        dis = api_get(PRAMS)

        if dis:
            discription = dis['query']['pages'][pageid]

            diagnosis = discription['title']
            page = 'https://en.wikipedia.org/wiki/'+diagnosis.replace(' ', '_')
            try:
                infobox = read_html(page, attrs={"class": "infobox"})[0].values
            except:
                return None
            else:

                infobox = dict((infobox[i][0], infobox[i][1])
                               for i in range(len(infobox)))
                try:
                    infobox['Diagnostic_method'] = infobox['Diagnostic method']
                    del infobox['Diagnostic method']
                except:
                    pass
                out = {"discription": discription, "infobox": infobox}
                return out
    try:
        title = get_title(diagnosis)
        info = get_info(title)
    except:
        return render(request, 'web/error.html', {'message': "no internet connection"})
    else:
        return render(request, 'web/diagnosis.html', {"title": title, "info": info, 'officials': od_list})


def processing(request):
    import tensorflow as tf
    import numpy as np
    model = tf.keras.models.load_model('web/datafiles/medical_prognosis.h5')
    input_field = np.zeros((1, 132))
    params = request.POST

    for a, b in params.items():
        try:
            a, b = int(a), int(b)

        except:
            pass
        else:
            input_field[0][a-1] = b

    pred = model.predict([input_field])
    result = np.argmax(pred, axis=1)
    # print("########--",input_field)

    prediction = read_csv("web/datafiles/diagnosis.csv",
                          header=None).values[:, 0][result][0]
    return HttpResponseRedirect(reverse('web:diagnosis', kwargs={'diagnosis': prediction}))


# -----------------auth----------
def login(request):
    return render(request, "web/login.html")


def login_auth(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        lg(request, user)

        return HttpResponseRedirect(reverse('web:officials'))
    else:
        return HttpResponseRedirect(reverse('web/login.html', kwargs={"error": "invalid login info"}))


@login_required(login_url="web/login")
def officials(request):
    illnesses = read_csv("web/datafiles/diagnosis.csv",
                         header=None).values[:, 0]
    message = ''
    usrname = request.user.username
    print(usrname)
    try:
        official = User.objects.get(username=usrname)
        diagnosis = request.POST['diagnosis']
        illness = request.POST['illness']
    except:
        check = False
    else:
        check = True
    if check:
        q = Official_Diagnosis(
            offical=official, diagnosis=diagnosis, illness=illness)
        q.save()
        message = "success"

    return render(request, 'web/officials.html', {'illnesses': illnesses, 'message': message})


def email(request):
    name = request.POST['firstname']+" "+request.POST['lastname']
    email_to = request.POST['email']
    subject = "MEDICAL DIAGNOSIS"
    email_from = "john@medic.com"
    message = "dear mr %s you most likely have ", name
    try:
        send_mail(
            subject,
            message,
            email_from,
            [email_to],

        )
    except:
        return render(request, "web/error.html")
    else:
        # return
        pass

medic/web/templates/web/error.html
<p>{{message}}</p>

medic/web/templates/web/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="Medic - Health and Medical HTML Template" />
    <meta name="author" content="potenzaglobalsolutions.com" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Medic - Health and Medical HTML Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'web/images/favicon.ico' %}" />

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap">

    <!-- CSS Global Compulsory (Do not remove)-->
    <link rel="stylesheet" href="{% static 'web/css/font-awesome/all.min.css' %} " />
    <link rel="stylesheet" href="{% static 'web/css/flaticon/flaticon.css' %}" />

    <!-- Template Style -->
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}" />

  </head>

  <body>

    <!--=================================
    header -->
    <header class="header header-01 header-sticky">
      <div class="main-header">
        <div class="container">
          <nav class="navbar navbar-static-top navbar-expand-lg">
            <a class="navbar-brand mr-0" href="index-2.html">
              <img class="img-fluid" src="images/logo.svg" alt="logo">
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse"><i class="fas fa-align-left"></i></button>
            <div class="navbar-collapse collapse justify-content-center">

            </div>
            <div class="add-listing d-none d-sm-block">
              <a class="btn btn-primary" href="#"><i class="fa fa-address-book"></i>Get a quote</a>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <!--=================================
    header -->


    <!--=================================
    login-->
    <section class="space-ptb">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-7 col-lg-9 col-md-10">
            <div class="login-form">
              <!-- Login form -->
              <form action="{% url 'web:login_auth' %}" method = 'post'>
                {% csrf_token %}
                <h3 class="mb-4 text-center text-primary">Login to your Account</h3>
                <div class="row align-items-center">
                  <div class="form-group col-md-12">
                    <input name = 'username' type="text" class="form-control" id="username" placeholder="Username">
                  </div>
                  <div class="form-group col-md-12">
                    <input name = "password" type="password" class="form-control" id="inputPassword" placeholder="Password">
                  </div>
                  <div class="form-group col-md-6">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" class="custom-control-input" id="customCheck1">
                      <label class="custom-control-label" for="customCheck1">Remember me</label>
                    </div>
                  </div>
                  <div class="form-group col-md-6 text-md-right">
                    <a href="#">Forget Password?</a>
                  </div>
                  <div class="form-group col-lg-12">
                  </div>
                  <div class="form-group col-sm-12 mb-0">
                    <button type="submit" class="btn btn-outline-primary my-3 my-sm-0">Login Now</button>
                  </div>
                </div>
              </form>
              <!-- Login form -->
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--=================================
    Contact-info-->



    <!--=================================
    footer-->
    <footer class="choose-people pb-0 footer bg-dark mt-lg-n5 mt-lg-0 mt-5">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <a href="index-2.html" class="footer-logo"><img class="img-fluid" src="images/logo-white.svg" alt=""></a>
            <p class="text-white">There’s nothing in this story to make us think he was dreaming about riches.</p>
            <div class="social-icon mt-3 mt-md-5">
              <ul>
                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                <li><a href="#"><i class="fab fa-github"></i></a></li>
                <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 mt-4 mt-md-0">
            <h6 class="text-primary">Useful Links</h6>
            <div class="footer-useful-List">
              <ul class="list-unstyled mb-0">
                <li><a href="about-us.html">About</a></li>
                <li><a href="team.html">Team</a></li>
                <li><a href="before-after.html">Before After</a></li>
                <li><a href="cost-calculator.html">Cost Calculator</a></li>
                <li><a href="working-hours.html">Working Hours</a></li>
              </ul>
              <ul class="list-unstyled mb-0">
                <li><a href="appointment.html">Appointment</a></li>
                <li><a href="gallery.html">Gallery</a></li>
                <li><a href="timetable.html">Timetable</a></li>
                <li><a href="departments.html">Departments</a></li>
                <li><a href="contact-us.html">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 mt-4 mt-lg-0 pr-4">
            <h6 class="text-primary">Our Newsletter</h6>
            <div class="footer-contact-info">
              <ul class="list-unstyled mb-0">
                <li><i class="fas fa-fw fa-map-marker-alt text-primary"></i><span class="text-white">594 E. Whitemarsh Street Mchenry, IL 60050</span></li>
                <li><i class="fas fa-fw fa-phone-alt text-primary"></i><span class="text-white">0123-456-789</span></li>
                <li><i class="fas fa-fw fa-headset text-primary"></i><span class="text-white">letstalk@medic.com</span></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 mt-4 mt-lg-0">
            <h6 class="text-primary">Subscribe Us</h6>
            <div class="footer-contact-info">
              <p class="text-white">Sign up to our newsletter to get the latest news and offers.</p>
              <form>
                <div class="form-group">
                  <input type="email" class="form-control" placeholder="Email*">
                </div>
                <button type="submit" class="btn btn-primary">Get Notified</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bottom">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-6 text-center copyright text-md-left mb-3 mb-md-0">
              <p class="mb-0 text-white"> &copy; Copyright <span id="copyright"> <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script></span> <a href="index-2.html"> medic </a> All Rights Reserved</p>
            </div>
            <div class="col-md-6 text-center text-md-right">
              <div class="">
                <ul class="list-unstyled list-inline mb-0">
                  <li class="list-inline-item mb-0"><a href="terms-and-conditions.html">Terms & Conditions</a></li>
                  <li class="list-inline-item mb-0"><a href="#">FAQ</a></li>
                  <li class="list-inline-item"><a href="privacy-policy.html">Privacy Policy</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!--=================================
    footer-->

    <!--=================================
    Javascript -->

    <!-- JS Global Compulsory (Do not remove)-->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>


    <!-- Template Scripts (Do not remove)--> 
    <script src="{% static 'js/custom.js' %}"></script>

  </body>

<!-- Mirrored from themes.potenzaglobalsolutions.com/html/medic/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 12 Jul 2022 12:38:56 GMT -->
</html>

medic/web/templates/web/symptoms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="Medic - Health and Medical HTML Template" />
    <meta name="author" content="potenzaglobalsolutions.com" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Medic - Health and Medical HTML Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'web/images/favicon.ico' %}" />

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap">

    <!-- CSS Global Compulsory (Do not remove)-->
    <link rel="stylesheet" href="{% static 'web/css/font-awesome/all.min.css' %} " />
    <link rel="stylesheet" href="{% static 'web/css/flaticon/flaticon.css' %}" />

    <!-- Page CSS Implementing Plugins (Remove the plugin CSS here if site does not use that feature)-->
    <link rel="stylesheet" href="{% static 'web/css/select2/select2.css' %}" />
    <link rel="stylesheet" href="{% static 'web/css/range-slider/ion.rangeSlider.css' %}" />
    <link rel="stylesheet" href="{% static 'web/css/owl-carousel/owl.carousel.min.css' %}" />

    <!-- Template Style -->
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}" />

  </head>

  <body>

    <!--=================================
    header -->
    <header class="header header-01 header-sticky">
      <div class="main-header">
        <div class="container">
          <nav class="navbar navbar-static-top navbar-expand-lg">
            <a class="navbar-brand mr-0" href="index-2.html">
              <img class="img-fluid" src="{% static 'web/images/logo.svg' %}" alt="logo">
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse"><i class="fas fa-align-left"></i></button>
            <div class="navbar-collapse collapse justify-content-center">
              <ul class="nav navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Shop <i class="fas fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="shop.html">Shop</a></li>
                    <li><a class="dropdown-item" href="shop-single.html">Shop Single</a></li>
                    <li><a class="dropdown-item" href="shop-cart.html">Shop Cart</a></li>
                    <li><a class="dropdown-item" href="shop-checkout.html">Shop Checkout</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="contact-us.html">
                    Contact Us
                  </a>
                </li>
              </ul>
            </div>
            <div class="add-listing d-none d-sm-block">
              <a class="btn btn-primary" href="#"><i class="fa fa-address-book"></i>Get a quote</a>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <!--=================================
    header -->

   

    <!--=================================
    blood -->
    <section class="space-pt">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-10 col-md-10 ">
            <div class="blood " >
              <!-- <h4 class="mb-4">Blood</h4> -->
              <form action="{% url 'web:processing' %}" method="post">
                {% csrf_token %}
                <div class="row align-items-center ">
                  <div class="form-group select-border col-md-12 ">
 <!-- ------------------------------------------------------- -->   
                    <link rel="stylesheet" href="{% static 'web/css/checkbox.css' %}">
                    <div class="bdy ">
                        <ul class="ks-cboxtags ">
                          {% for symp in symptoms_list %}
                          <li>
                            <input name ={{forloop.counter}} value=1 type="checkbox" class=" btn-c-check" id="checkbox{{forloop.counter}}">
                            <label for="checkbox{{forloop.counter}}" class="btn-c ">{{symp}}</label>
                        </li> 
                          {% endfor %}  
                        </ul>
                    </div>
                    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
 <!-- ------------------------------------------------------ -->
                  </div>
                  <div class="form-group col-md-12 cost-price">

                  </div>
              </div>
                <div class="text-right m-2 ">
                  <button type="submit"  class="btn blood-amount">Done</button>
              </div>
              <!-- <button  class="btn btn-primary">Get Notified</button> -->

              </form>
            </div>

          </div>
        </div>
      </div>
    </section>
    <!--=================================
    blood -->

   




    <!--=================================
    footer-->
    <footer class="choose-people pb-0 footer bg-dark mt-lg-n5 mt-lg-0 mt-5">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <a href="index-2.html" class="footer-logo"><img class="img-fluid" src="images/logo-white.svg" alt=""></a>
            <p class="text-white">There’s nothing in this story to make us think he was dreaming about riches.</p>
            <div class="social-icon mt-3 mt-md-5">
              <ul>
                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                <li><a href="#"><i class="fab fa-github"></i></a></li>
                <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 mt-4 mt-md-0">
            <h6 class="text-primary">Useful Links</h6>
            <div class="footer-useful-List">
              <ul class="list-unstyled mb-0">
                <li><a href="about-us.html">About</a></li>
                <li><a href="team.html">Team</a></li>
                <li><a href="before-after.html">Before After</a></li>
                <li><a href="cost-calculator.html">Cost Calculator</a></li>
                <li><a href="working-hours.html">Working Hours</a></li>
              </ul>
              <ul class="list-unstyled mb-0">
                <li><a href="appointment.html">Appointment</a></li>
                <li><a href="gallery.html">Gallery</a></li>
                <li><a href="timetable.html">Timetable</a></li>
                <li><a href="departments.html">Departments</a></li>
                <li><a href="contact-us.html">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 mt-4 mt-lg-0 pr-4">
            <h6 class="text-primary">Our Newsletter</h6>
            <div class="footer-contact-info">
              <ul class="list-unstyled mb-0">
                <li><i class="fas fa-fw fa-map-marker-alt text-primary"></i><span class="text-white">594 E. Whitemarsh Street Mchenry, IL 60050</span></li>
                <li><i class="fas fa-fw fa-phone-alt text-primary"></i><span class="text-white">0123-456-789</span></li>
                <li><i class="fas fa-fw fa-headset text-primary"></i><span class="text-white">letstalk@medic.com</span></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 mt-4 mt-lg-0">
            <h6 class="text-primary">Subscribe Us</h6>
            <div class="footer-contact-info">
              <p class="text-white">Sign up to our newsletter to get the latest news and offers.</p>
              <form>
                <div class="form-group">
                  <input type="email" class="form-control" placeholder="Email*">
                </div>
                <button type="submit" class="btn btn-primary">Get Notified</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bottom">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-6 text-center copyright text-md-left mb-3 mb-md-0">
              <p class="mb-0 text-white"> &copy; Copyright <span id="copyright"> <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script></span> <a href="index-2.html"> medic </a> All Rights Reserved</p>
            </div>
            <div class="col-md-6 text-center text-md-right">
              <div class="">
                <ul class="list-unstyled list-inline mb-0">
                  <li class="list-inline-item mb-0"><a href="terms-and-conditions.html">Terms & Conditions</a></li>
                  <li class="list-inline-item mb-0"><a href="#">FAQ</a></li>
                  <li class="list-inline-item"><a href="privacy-policy.html">Privacy Policy</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!--=================================
    footer-->

    <!--=================================
    Javascript -->

    <!-- JS Global Compulsory (Do not remove)-->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>

    <!-- Page JS Implementing Plugins (Remove the plugin script here if site does not use that feature)-->
    <script src="{% static 'js/select2/select2.full.js' %}"></script>

    <!-- Template Scripts (Do not remove)--> 
    <script src="{% static 'js/custom.js' %}"></script>
  </body>

</html>